name: golangci-lint
on:
  push:
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          check-latest: true
      - uses: actions/checkout@v5
      - run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          # args: --issues-exit-code=0
          only-new-issues: true
