on: [push, pull_request]
name: Test
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.5]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: go test -v
