on: [push, pull_request]
name: Test
jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.16.x', 'stable']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true
    - name: Test
      run: go test -v
